### ISSUE TITLE
Add placeholder for SIG Governance Document

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/sig-interoperability#5]
SIG governance needs to be documented and made available for the community.

This issue is just adding a placeholder for such a document rather than creating it. The reason for this is that we need to clarify if CDF TOC should have SIG governance documented which all the SIGs are bound or not. If TOC decides to have one, we can refer to it rather than creating our own.

To clarify this, an issue has been created in CDF TOC repository. [0] Depending on the outcome of that discussion, we can then decide what to do.

[0] https://github.com/cdfoundation/toc/issues/70

**Comment by fdegir** [comment]
@MarckK This issue was created some time ago and since you took the action point during the lmeeting to get the document started, you can perhaps either take this issue over and update the subject and details or close this and create a new one.

What do you think?

**Comment by MarckK** [comment]
It would likely be better if the governance flowed downwards and all 'descendent' groups at the same level had roughly the same governance as outlined by their 'parent'.

With this in mind, I've started a governance doc for the Interoperability SIG Workstream groups that are forming and have raised it as PR https://github.com/cdfoundation/sig-interoperability/pull/33.

**Comment by fdegir** [comment]
It seems we've missed closing this. Thanks for getting workstream governance in place @MarckK.
