### ISSUE TITLE
Slack invitation broken

### ISSUE THREAD

**Issue by cachedout** [cdfoundation/sig-interoperability#61]
Just watched the talk on the CD Foundation at FOSDEM. (Really great!)

I wanted to jump into the Slack but it looks like the link isn't working. Here is what I get when I go to the link that's currently in the README:

<img width="632" alt="Capture d’écran 2021-02-07 à 10 33 07" src="https://user-images.githubusercontent.com/111616/107142525-9c308a80-6927-11eb-8a6f-da45df40ecd1.png">

Could somebody please look into this? Thanks!

**Comment by fdegir** [comment]
Thanks for reporting this @cachedout.

Can you please try the link below to see if it works?

https://cdeliveryfdn.slack.com/archives/CSNV2UQ5C

**Comment by fdegir** [comment]
The link is replaced with the one above in readme as well.

https://github.com/cdfoundation/sig-interoperability/commit/52968a5a92c496501a4d8a813785f9aac82ccfed

@cachedout please let me know if you could join via the link so we can close the issue.
Thanks again for reporting and joining our talk during FOSDEM.

**Comment by cachedout** [comment]
@fdegir Thanks for the quick reply! Sadly, the new link produces the same result as the old one, so I still can't get in.

**Comment by fdegir** [comment]
@cachedout sorry for that.

@tracymiranda @MarckK The one I generated above didn't work so I can't seem to generate Slack invite. Can you generate one please?

**Comment by MarckK** [comment]
Hi @cachedout,

To join the CDF slack, please try this link: https://join.slack.com/t/cdeliveryfdn/shared_invite/enQtODM2NDI1NDc0MzIxLTA1MDcxMzUyMGU2NWVlNmQwN2M1N2M4MWJjOWFkM2UzMDY0OWNkNjAzNzM0NzVkNjQ5M2NkMmY2MTRkMWY4MWY

Let us know if that helps!

**Comment by cachedout** [comment]
@MarckK Hrm. Well, good news / bad news. When using the Google SSO option from that link it still shows as expired. However, when using the option to provide an email address directly, it seems to have worked. So, perhaps this is a transient issue on Slack's end? Either way, I'm in now so I will go ahead and close this. Thanks for the help!

**Comment by MarckK** [comment]
Awesome! 
Welcome to the Interoperability SIG, @cachedout 😃
